"""empty message

Revision ID: dcee2a1034c6
Revises: 
Create Date: 2018-01-24 18:24:11.120708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcee2a1034c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_products',
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('comsumer_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('product_id', 'comsumer_id')
    )
    op.create_table('used_products',
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('comsumer_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('product_id', 'comsumer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_products')
    op.drop_table('available_products')
    # ### end Alembic commands ###
